site:
  title: Scribe
  url: https://amdphreak.github.io/scribe
  start_page: docs::index.adoc

content:
  sources:
    - url: ./
      branches: HEAD
      start_path: docs

ui:
  bundle:
    url: https://registry.npmjs.org/antora-dark-theme/-/antora-dark-theme-0.1.4.tgz
  supplemental_files: ./site/src

output:
  dir: site/dist/docs
