site:
  title: Scribe
  url: https://amdphreak.github.io/scribe
  start_page: docs::index.adoc

content:
  sources:
    - url: ./
      branches: HEAD
      start_path: docs

ui:
  bundle:
    url: https://github.com/antora-supplemental/antora-dark-theme/releases/latest/download/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - ./site/src

output:
  dir: site/dist
